name: Flujo de trabajo1
on: [push]

jobs:
  # poniendo un nombre a nuestro job
  prueba1:
    # le diremos que instale en su última versión al Ubuntu
    runs-on: ubuntu-latest

    # ahora crearé los steps
    steps:
      # el primer step será un checkout (opcional, pero recomendado)
      - name: Mensaje
        uses: actions/checkout@v4

      # el segundo step será imprimir un mensaje
      - run: echo "Mi primera iteración con GitHub Actions"
