name: Flujo de trabajo1
on: [push]

jobs:
  # poniendo un nombre a nuestro job
  prueba1:
    # le diremos que instale en su última versión al Ubuntu
    runs-on: ubuntu-latest

    # ahora crearé los steps
    steps:
      # el primer step será un checkout (opcional, pero recomendado)
      - name: Mensaje
        uses: actions/checkout@v4

      # el segundo step será imprimir un mensaje
      - run: echo "Mi primera iteración con GitHub Actions"
      
      # se va crear un nuevo archivo
      - name: crear archivo
        run: touch alumnos.txt

      # agregar alumnos
      - name: agregar alumno
        run: |
          echo "Juan Perez" >> alumnos.txt
          echo "Maria Garcia" >> alumnos.txt
          echo "Carlos Lopez" >> alumnos.txt

      # mostrar alumnos
      - name: mostrar alumnos
        run: cat alumnos.txt


  #  creando otro jobs con nombre prueba 2
  prueba2:
    runs-on: ubuntu-latest
    steps:
      - name: muestra cambios de alumnos
        run: cat alumnos.txt
