name: Flujo de trabajo1
on: [push]

jobs:
  prueba1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - run: echo "Mi primera iteración con GitHub Actions"

      - name: Crear archivo alumnos.txt
        run: touch alumnos.txt

      - name: Agregar alumnos
        run: |
          echo "Juan Perez" >> alumnos.txt
          echo "Maria Garcia" >> alumnos.txt
          echo "Carlos Lopez" >> alumnos.txt

      - name: Mostrar alumnos
        run: cat alumnos.txt

      # Subir el archivo como artifact para que pueda ser usado en el siguiente job
      - name: Guardar archivo alumnos.txt
        uses: actions/upload-artifact@v4  # Actualizado a v4
        with:
          name: alumnos  # Nombre del artifact
          path: alumnos.txt

  prueba2:
    runs-on: ubuntu-latest
    needs: prueba1  # Asegura que este job espere a que 'prueba1' termine correctamente
    steps:
      - name: Descargar archivo alumnos.txt
        uses: actions/download-artifact@v4  # Actualizado a v4
        with:
          name: alumnos  # Este debe ser el mismo nombre que el usado al subir el artifact

      - name: Mostrar cambios de alumnos
        run: cat alumnos.txt
