name: corriendo-servicios
on:
  push:
    branches:
      - grato390

jobs:
  trabajo1:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: prueba
          MYSQL_USER: usuario
          MYSQL_PASSWORD: password
        options: --health-cmd="mysqladmin ping --host=127.0.0.1 --user=root --password=root" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Verificar conexión a MySQL
        run: |
          sudo apt-get install -y mysql-client
          mysql --host=127.0.0.1 --user=root --password=root -e "SHOW DATABASES;"
