name: corriendo-servicios
on:
  push:
    branches:
      - grato390

jobs:
  trabajo1:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: prueba
        ports:
          - 3306:3306  # Mapeo del puerto para MySQL

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Esperar que MySQL inicie
        run: sleep 15

      - name: Instalar cliente MySQL
        run: sudo apt-get install -y mysql-client

      - name: Verificar conexión a MySQL
        run: |
          mysql --host=127.0.0.1 --port=3306 --user=root --password=root -e "SHOW DATABASES;"
